const textos = {
    usuario: "Usuario",
    nombre: "Nombre",
    apellidos: "Apellidos",
    telefono: "Telefono",
    correo: "Correo",
    contraseña: "Contraseña",
    boton: "Registrarse",
    botonIniciarSesion: "Iniciar sesion",
    registarse: "Crear cuenta",
    botonCerrar: "X",
    botonIniciarHeader: "Iniciar en cuenta",
    mensajeIniciarHeader: "PARA COMPRAR DEBES ENTRAR EN UNA CUENTA",
    noFlores: "CANTIDAD DE FLORES",
    color: "COLOR",
    ramoDe: "RAMO DE GERBERAS",
    pzs: "6 Pz",
    detalles: "Detalles del pedido",
    orden: "Orden",
    envio: "Envio",
    total: "Total",
    ubicacion: "Ubicacion:",
    elegirOpc: "Elige el lugar donde quieres recibir tu pedido",
    metodosPago: "Metodos de pago",
    transferencia: "Transferencia bancaria",
    conceptoPago: "Concepto de pago: ",
    errorInput:"no ingrese numeros negativos u otros caracteres",
    textoHeader: {
        titulo: "Detalles Tere",
        opc1: "Comprar",
        opc2: "productos",
        opc3: "Ventas",
        opc4: "Contacto",
        comprar: "Comprar ahora",
       
    },
    textoBotones: {
        botonPrev: "Anterior",
        botonNext: "Siguiente",
        editar: "Editar",
        guardar: "Guardar",
        crearUsuarioVacio: "debes llenar todos los campos",
        ok: "OK",
        datosIncorrectos: "Usuario o contraseña incorrectos",
        lugar1: "Parada ruta verde",
        lugar2: "Parada ruta azul",
        lugar3: "Parada ruta via teran",
        lugar4: "Universidad Politecnica de Chiapas",
        realizarPedido: "Realizar Pedido",
        aceptar: "Aceptar",
        rechazar: "Rechazar",
        verProductos: "Ver productos",
        verPedidos: "Ver pedidos",
        reporteVentas: "Ver reporte de ventas",
        comprarProducto:"Comprar",
        pagar:"Pagar",
        continuar:"Continuar",
    },
    tabla: {
        col1: "Concepto de pago",
        col2:"Codigo del producto vendido",
        col3:"Nombre del produco",
        col4:"Especificaciones",
        col5:"Nombre del usuario que compro",
        col6:"Fecha de compra",
        col7:"Costo de envio",
        col8:"Costo del producto",
        col9:"Total",
    }
}

export default textos;
